# Generated by Django 5.2.5 on 2025-09-14 01:09

import core.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criados",
                    models.DateField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("cargo", models.CharField(max_length=100, verbose_name="Cargo")),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criados",
                    models.DateField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("nome", models.CharField(max_length=30, verbose_name="Nome")),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                ("mensagem", models.CharField(max_length=300, verbose_name="Mensagem")),
                ("nota", models.IntegerField(verbose_name="Nota")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={"thumb": {"crop": True, "height": 72, "width": 72}},
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criados",
                    models.DateField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("lni-rocket", "Foguete"),
                            ("lni-laptop-phone", "Usuários"),
                            ("lni-cog", "Engrenagem"),
                            ("lni-layers", "Design"),
                            ("lni-stats-up", "Template"),
                            ("lni-mobile", "Formulário"),
                        ],
                        max_length=20,
                        verbose_name="Icone",
                    ),
                ),
                ("feature", models.CharField(max_length=100, verbose_name="Feature")),
                (
                    "descricao",
                    models.TextField(max_length=300, verbose_name="Descricao"),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
            },
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criados",
                    models.DateField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("servico", models.CharField(max_length=100, verbose_name="Serviço")),
                (
                    "descricao",
                    models.TextField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("lni-cog", "Engrenagem"),
                            ("lni-stats-up", "Gráfico"),
                            ("lni-users", "Usuários"),
                            ("lni-layers", "Design"),
                            ("lni-mobile", "Mobile"),
                            ("lni-rocket", "Foguete"),
                        ],
                        max_length=12,
                        verbose_name="Icone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criados",
                    models.DateField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("bio", models.TextField(max_length=300, verbose_name="Biografia")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        default="#", max_length=100, verbose_name="Facebook"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        default="#", max_length=100, verbose_name="Twitter"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        default="#", max_length=100, verbose_name="Instagram"
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cargo",
                        verbose_name="Cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
    ]
