# Generated by Django 5.2.5 on 2025-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="bio",
            field=models.TextField(max_length=300, verbose_name="Biografia"),
        ),
    ]
