# Generated by Django 5.2.5 on 2025-09-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_funcionario_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo?"),
        ),
        migrations.AddField(
            model_name="cargo",
            name="criados",
            field=models.DateField(
                auto_now_add=True, default="2025-09-08", verbose_name="Criação"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargo",
            name="modificado",
            field=models.DateField(auto_now=True, verbose_name="Atualização"),
        ),
    ]
