# Generated by Django 5.2.5 on 2025-09-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_funcionario_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="instagram",
            field=models.CharField(
                default="#", max_length=100, verbose_name="Instagram"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="twitter",
            field=models.CharField(default="#", max_length=100, verbose_name="Twitter"),
        ),
    ]
