# Generated by Django 5.2.5 on 2025-09-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_funcionario_instagram_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criados",
                    models.DateField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("lni-rocket", "Foguete"),
                            ("lni-users", "Usuários"),
                            ("lni-cog", "Engrenagem"),
                            ("lni-layers", "Design"),
                            ("lni-stats-up", "Template"),
                            ("fa-file-alt", "Formulário"),
                        ],
                        max_length=12,
                        verbose_name="Icone",
                    ),
                ),
                ("feature", models.CharField(max_length=100, verbose_name="Feature")),
                (
                    "descricao",
                    models.TextField(max_length=300, verbose_name="Descricao"),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
            },
        ),
    ]
