# Generated by Django 5.2.5 on 2025-09-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="icone",
            field=models.CharField(
                choices=[
                    ("lni-rocket", "Foguete"),
                    ("lni-desktop", "Usuários"),
                    ("lni-cog", "Engrenagem"),
                    ("lni-layers", "Design"),
                    ("lni-stats-up", "Template"),
                    ("lni-file-add", "Formulário"),
                ],
                max_length=12,
                verbose_name="Icone",
            ),
        ),
    ]
