"""
Django settings for fusion project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url  # utilizado para que servidor possa ler as informações
# do host e utilizar o banco de dados.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-l!to&%w!&3d@(ihn35b--*r_vr$a^^#-x$oxk-xlm%&o*h0@3l"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["fusion-bvs.onrender.com/"]


# Application definition

INSTALLED_APPS = [
    "core",
    #"django adminlte",  # Adiciona admin
    #"django adminlte theme",  # Adiciona novo tema
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",


]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "fusion.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fusion.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "fusion",
        "USER": "geek",
        "PASSWORD": "university",
        "HOST": "localhost",
        "PORT": "5432",
    }
}
"""

# dj_database_url.config() -> vai ler por padrão as configurações de conexão do
# servidor da hospedagem e vai passar os dados para acesso ao banco de dados.
DATABASES = {
    'default': dj_database_url.config(
        default="postgresql://fusion_db_1wgv_user:OLt9RskPNJhcZTMJXavO7zWfqUXTOm7S@dpg-d34qpt63jp1c73ehel8g-a.oregon-postgres.render.com/fusion_db_1wgv",
        conn_max_age=600,
        conn_health_checks=True, test_options={'NAME': 'fusion-db'}
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Porto_Velho"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/media/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Email teste console
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

"""
# Email produção

EMAIL_HOST = 'localhost'  # servidor local que vai enviar o email
EMAIL_HOST_USER = 'no-reply@fusion.com.br'  # Usuário de autenticação de e-mail
EMAIL_PORT = 587  # Porta que vai estar rodando o e-mail
EMAIL_USE_TSL = True  # Vai usar segurança
EMAIL_HOST_PASSWORD = 'fusion'  # Senha de usuário
DEFAULT_FROM_EMAIL = 'contato@fusion.com.br'  # E-mail de contato
"""


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Se caso algum superusuário esteja logado no painel administrativo, vai ser
# redirecionado para página index.
LOGOUT_REDIRECT_URL = "index"
